name: Windows

on:
  push:
    paths:
      - "CMakeLists.txt"
      - "**/workflows/build_windows.yml"
      - "**/cmake/**"
      - "**/examples/**"
      - "**/modules/**"
      - "**/tests/**"
      - "**/thirdparty/**"
      - "!**/native/generated/**"
      - "!**/native/java*/**"
      - "!**/native/*_android.*"
      - "!**/native/*_apple.*"
      - "!**/native/*_emscripten.*"
      - "!**/native/*_linux.*"
      - "!**/native/*_ios.*"
      - "!**/native/*_mac.*"
      - "!**/native/*_posix.*"
      - "!**/native/*_wasm.*"
    branches:
      - "**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_tests:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - run: cmake ${{ github.workspace }} -B ${{ runner.workspace }}/build -DYUP_ENABLE_TESTS=ON
    - run: cmake --build ${{ runner.workspace }}/build --config Debug --parallel 4 --target yup_tests
    - working-directory: ${{ runner.workspace }}/build/tests/Debug
      run: ./yup_tests.exe
    - run: cmake --build ${{ runner.workspace }}/build --config Release --parallel 4 --target yup_tests
    - working-directory: ${{ runner.workspace }}/build/tests/Release
      run: ./yup_tests.exe

  build_console:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - run: cmake ${{ github.workspace }} -B ${{ runner.workspace }}/build -DYUP_ENABLE_EXAMPLES=ON
    - run: cmake --build ${{ runner.workspace }}/build --config Debug --parallel 4 --target example_console
    - run: cmake --build ${{ runner.workspace }}/build --config Release --parallel 4 --target example_console

  build_app:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - run: cmake ${{ github.workspace }} -B ${{ runner.workspace }}/build -DYUP_ENABLE_EXAMPLES=ON
    - run: cmake --build ${{ runner.workspace }}/build --config Debug --parallel 4 --target example_app
    - run: cmake --build ${{ runner.workspace }}/build --config Release --parallel 4 --target example_app

  build_graphics:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - run: cmake ${{ github.workspace }} -B ${{ runner.workspace }}/build -DYUP_ENABLE_EXAMPLES=ON
    - run: cmake --build ${{ runner.workspace }}/build --config Debug --parallel 4 --target example_graphics
    - run: cmake --build ${{ runner.workspace }}/build --config Release --parallel 4 --target example_graphics

  build_plugin:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - run: cmake ${{ github.workspace }} -B ${{ runner.workspace }}/build -DYUP_ENABLE_EXAMPLES=ON
    - run: cmake --build ${{ runner.workspace }}/build --config Debug --parallel 4 --target example_plugin_clap_plugin
    - run: cmake --build ${{ runner.workspace }}/build --config Release --parallel 4 --target example_plugin_clap_plugin
    #- run: cmake --build ${{ runner.workspace }}/build --config Debug --parallel 4 --target example_plugin_vst3_plugin
    #- run: cmake --build ${{ runner.workspace }}/build --config Release --parallel 4 --target example_plugin_vst3_plugin
    - run: cmake --build ${{ runner.workspace }}/build --config Debug --parallel 4 --target example_plugin_standalone_plugin
    - run: cmake --build ${{ runner.workspace }}/build --config Release --parallel 4 --target example_plugin_standalone_plugin
