name: MacOS

on:
  push:
    paths:
      - "CMakeLists.txt"
      - "**/workflows/build_macos.yml"
      - "**/cmake/**"
      - "**/examples/**"
      - "**/modules/**"
      - "**/tests/**"
      - "**/thirdparty/**"
      - "!**/native/*_android.*"
      - "!**/native/*_emscripten.*"
      - "!**/native/*_linux.*"
      - "!**/native/*_ios.*"
      - "!**/native/*_wasm.*"
      - "!**/native/*_windows.*"
    branches:
      - "**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  DEVELOPER_DIR: /Applications/Xcode_15.1.app/Contents/Developer

jobs:
  configure:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - uses: seanmiddleditch/gha-setup-ninja@master

    - name: Configure
      run: cmake ${{ github.workspace }} -G "Ninja Multi-Config" -B ${{ runner.workspace }}/build -DYUP_ENABLE_TESTS=ON -DYUP_ENABLE_EXAMPLES=ON

    - name: Build SDL2
      run: |
        cmake --build ${{ runner.workspace }}/build --config Debug --parallel 4 --target SDL2-static
        cmake --build ${{ runner.workspace }}/build --config Release --parallel 4 --target SDL2-static

    - name: Cache Configure
      id: cache-build
      uses: actions/cache/save@v4
      with:
        path: ${{ runner.workspace }}/build
        key: macos-build-${{ github.sha }}

  build_tests:
    runs-on: macos-latest
    needs: [configure]
    steps:
    - uses: actions/checkout@v4
    - uses: seanmiddleditch/gha-setup-ninja@master
    - uses: actions/cache/restore@v4
      id: cache-restore
      with:
        path: ${{ runner.workspace }}/build
        key: macos-build-${{ github.sha }}
    - name: Configure If Cache Missed
      if: steps.cache-restore.outputs.cache-hit != 'true'
      run: cmake ${{ github.workspace }} -G "Ninja Multi-Config" -B ${{ runner.workspace }}/build -DYUP_ENABLE_TESTS=ON
    - run: cmake --build ${{ runner.workspace }}/build --config Debug --parallel 4 --target yup_tests
    - working-directory: ${{ runner.workspace }}/build/tests/Debug
      run: ./yup_tests.app/Contents/MacOS/yup_tests
    - run: cmake --build ${{ runner.workspace }}/build --config Release --parallel 4 --target yup_tests
    - working-directory: ${{ runner.workspace }}/build/tests/Release
      run: ./yup_tests.app/Contents/MacOS/yup_tests

  build_console:
    runs-on: macos-latest
    needs: [configure]
    steps:
    - uses: actions/checkout@v4
    - uses: seanmiddleditch/gha-setup-ninja@master
    - uses: actions/cache/restore@v4
      id: cache-restore
      with:
        path: ${{ runner.workspace }}/build
        key: macos-build-${{ github.sha }}
    - name: Configure If Cache Missed
      if: steps.cache-restore.outputs.cache-hit != 'true'
      run: cmake ${{ github.workspace }} -G "Ninja Multi-Config" -B ${{ runner.workspace }}/build -DYUP_ENABLE_EXAMPLES=ON
    - run: cmake --build ${{ runner.workspace }}/build --config Debug --parallel 4 --target example_console
    - run: cmake --build ${{ runner.workspace }}/build --config Release --parallel 4 --target example_console

  build_app:
    runs-on: macos-latest
    needs: [configure]
    steps:
    - uses: actions/checkout@v4
    - uses: seanmiddleditch/gha-setup-ninja@master
    - uses: actions/cache/restore@v4
      id: cache-restore
      with:
        path: ${{ runner.workspace }}/build
        key: macos-build-${{ github.sha }}
    - name: Configure If Cache Missed
      if: steps.cache-restore.outputs.cache-hit != 'true'
      run: cmake ${{ github.workspace }} -G "Ninja Multi-Config" -B ${{ runner.workspace }}/build -DYUP_ENABLE_EXAMPLES=ON
    - run: cmake --build ${{ runner.workspace }}/build --config Debug --parallel 4 --target example_app
    - run: cmake --build ${{ runner.workspace }}/build --config Release --parallel 4 --target example_app

  build_graphics:
    runs-on: macos-latest
    needs: [configure]
    steps:
    - uses: actions/checkout@v4
    - uses: seanmiddleditch/gha-setup-ninja@master
    - uses: actions/cache/restore@v4
      id: cache-restore
      with:
        path: ${{ runner.workspace }}/build
        key: macos-build-${{ github.sha }}
    - name: Configure If Cache Missed
      if: steps.cache-restore.outputs.cache-hit != 'true'
      run: cmake ${{ github.workspace }} -G "Ninja Multi-Config" -B ${{ runner.workspace }}/build -DYUP_ENABLE_EXAMPLES=ON
    - run: cmake --build ${{ runner.workspace }}/build --config Debug --parallel 4 --target example_graphics
    - run: cmake --build ${{ runner.workspace }}/build --config Release --parallel 4 --target example_graphics

  build_plugins:
    runs-on: macos-latest
    needs: [configure]
    steps:
    - uses: actions/checkout@v4
    - uses: seanmiddleditch/gha-setup-ninja@master
    - uses: actions/cache/restore@v4
      id: cache-restore
      with:
        path: ${{ runner.workspace }}/build
        key: macos-build-${{ github.sha }}
    - name: Configure If Cache Missed
      if: steps.cache-restore.outputs.cache-hit != 'true'
      run: cmake ${{ github.workspace }} -G "Ninja Multi-Config" -B ${{ runner.workspace }}/build -DYUP_ENABLE_EXAMPLES=ON
    - run: cmake --build ${{ runner.workspace }}/build --config Debug --parallel 4 --target example_plugin_clap_plugin
    - run: cmake --build ${{ runner.workspace }}/build --config Release --parallel 4 --target example_plugin_clap_plugin
    - run: cmake --build ${{ runner.workspace }}/build --config Debug --parallel 4 --target example_plugin_vst3_plugin
    - run: cmake --build ${{ runner.workspace }}/build --config Release --parallel 4 --target example_plugin_vst3_plugin
    - run: cmake --build ${{ runner.workspace }}/build --config Debug --parallel 4 --target example_plugin_standalone_plugin
    - run: cmake --build ${{ runner.workspace }}/build --config Release --parallel 4 --target example_plugin_standalone_plugin
