name: Linux

on:
  push:
    paths:
      - "CMakeLists.txt"
      - "**/workflows/build_linux.yml"
      - "**/cmake/**"
      - "**/examples/**"
      - "**/modules/**"
      - "**/tests/**"
      - "**/thirdparty/**"
      - "!**/native/generated/**"
      - "!**/native/java*/**"
      - "!**/native/*_android.*"
      - "!**/native/*_apple.*"
      - "!**/native/*_emscripten.*"
      - "!**/native/*_ios.*"
      - "!**/native/*_mac.*"
      - "!**/native/*_wasm.*"
      - "!**/native/*_windows.*"
    branches:
      - "**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  INSTALL_DEPS: >-
    libasound2-dev libjack-jackd2-dev ladspa-sdk libcurl4-openssl-dev libfreetype6-dev
    libx11-dev libxcomposite-dev libxcursor-dev libxcursor-dev libxext-dev libxi-dev libxinerama-dev
    libxrandr-dev libxrender-dev libglu1-mesa-dev libegl1-mesa-dev mesa-common-dev

jobs:
  configure:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: seanmiddleditch/gha-setup-ninja@master
    - name: Install Dependencies
      run: sudo apt-get update && sudo apt-get install -y ${INSTALL_DEPS}

    - name: Configure
      run: cmake ${{ github.workspace }} -G "Ninja Multi-Config" -B ${{ runner.workspace }}/build -DYUP_ENABLE_TESTS=ON -DYUP_ENABLE_EXAMPLES=ON

    - name: Build SDL2
      run: |
        cmake --build ${{ runner.workspace }}/build --config Debug --parallel 4 --target SDL2-static
        cmake --build ${{ runner.workspace }}/build --config Release --parallel 4 --target SDL2-static

    - name: Cache Configure
      id: cache-build
      uses: actions/cache/save@v4
      with:
        path: ${{ runner.workspace }}/build
        key: linux-build-${{ github.sha }}

  build_tests:
    runs-on: ubuntu-latest
    needs: [configure]
    steps:
    - uses: actions/checkout@v4
    - uses: seanmiddleditch/gha-setup-ninja@master
    - run: sudo apt-get update && sudo apt-get install -y ${INSTALL_DEPS}
    - uses: actions/cache/restore@v4
      id: cache-restore
      with:
        path: ${{ runner.workspace }}/build
        key: linux-build-${{ github.sha }}
    - name: Configure If Cache Missed
      if: steps.cache-restore.outputs.cache-hit != 'true'
      run: cmake ${{ github.workspace }} -G "Ninja Multi-Config" -B ${{ runner.workspace }}/build -DYUP_ENABLE_TESTS=ON
    - run: cmake --build ${{ runner.workspace }}/build --config Debug --parallel 4 --target yup_tests
    - working-directory: ${{ runner.workspace }}/build/tests/Debug
      run: ./yup_tests
    - run: cmake --build ${{ runner.workspace }}/build --config Release --parallel 4 --target yup_tests
    - working-directory: ${{ runner.workspace }}/build/tests/Release
      run: ./yup_tests

  build_console:
    runs-on: ubuntu-latest
    needs: [configure]
    steps:
    - uses: actions/checkout@v4
    - uses: seanmiddleditch/gha-setup-ninja@master
    - run: sudo apt-get update && sudo apt-get install -y ${INSTALL_DEPS}
    - uses: actions/cache/restore@v4
      id: cache-restore
      with:
        path: ${{ runner.workspace }}/build
        key: linux-build-${{ github.sha }}
    - name: Configure If Cache Missed
      if: steps.cache-restore.outputs.cache-hit != 'true'
      run: cmake ${{ github.workspace }} -G "Ninja Multi-Config" -B ${{ runner.workspace }}/build -DYUP_ENABLE_EXAMPLES=ON
    - run: cmake --build ${{ runner.workspace }}/build --config Debug --parallel 4 --target example_console
    - run: cmake --build ${{ runner.workspace }}/build --config Release --parallel 4 --target example_console

  build_app:
    runs-on: ubuntu-latest
    needs: [configure]
    steps:
    - uses: actions/checkout@v4
    - uses: seanmiddleditch/gha-setup-ninja@master
    - run: sudo apt-get update && sudo apt-get install -y ${INSTALL_DEPS}
    - uses: actions/cache/restore@v4
      id: cache-restore
      with:
        path: ${{ runner.workspace }}/build
        key: linux-build-${{ github.sha }}
    - name: Configure If Cache Missed
      if: steps.cache-restore.outputs.cache-hit != 'true'
      run: cmake ${{ github.workspace }} -G "Ninja Multi-Config" -B ${{ runner.workspace }}/build -DYUP_ENABLE_EXAMPLES=ON
    - run: cmake --build ${{ runner.workspace }}/build --config Debug --parallel 4 --target example_app
    - run: cmake --build ${{ runner.workspace }}/build --config Release --parallel 4 --target example_app

  build_graphics:
    runs-on: ubuntu-latest
    needs: [configure]
    steps:
    - uses: actions/checkout@v4
    - uses: seanmiddleditch/gha-setup-ninja@master
    - run: sudo apt-get update && sudo apt-get install -y ${INSTALL_DEPS}
    - uses: actions/cache/restore@v4
      id: cache-restore
      with:
        path: ${{ runner.workspace }}/build
        key: linux-build-${{ github.sha }}
    - name: Configure If Cache Missed
      if: steps.cache-restore.outputs.cache-hit != 'true'
      run: cmake ${{ github.workspace }} -G "Ninja Multi-Config" -B ${{ runner.workspace }}/build -DYUP_ENABLE_EXAMPLES=ON
    - run: cmake --build ${{ runner.workspace }}/build --config Debug --parallel 4 --target example_graphics
    - run: cmake --build ${{ runner.workspace }}/build --config Release --parallel 4 --target example_graphics

  build_plugin:
    runs-on: ubuntu-latest
    needs: [configure]
    steps:
    - uses: actions/checkout@v4
    - uses: seanmiddleditch/gha-setup-ninja@master
    - run: sudo apt-get update && sudo apt-get install -y ${INSTALL_DEPS}
    - uses: actions/cache/restore@v4
      id: cache-restore
      with:
        path: ${{ runner.workspace }}/build
        key: linux-build-${{ github.sha }}
    - name: Configure If Cache Missed
      if: steps.cache-restore.outputs.cache-hit != 'true'
      run: cmake ${{ github.workspace }} -G "Ninja Multi-Config" -B ${{ runner.workspace }}/build -DYUP_ENABLE_EXAMPLES=ON
    - run: cmake --build ${{ runner.workspace }}/build --config Debug --parallel 4 --target example_plugin_clap_plugin
    - run: cmake --build ${{ runner.workspace }}/build --config Release --parallel 4 --target example_plugin_clap_plugin
    #- run: cmake --build ${{ runner.workspace }}/build --config Debug --parallel 4 --target example_plugin_vst3_plugin
    #- run: cmake --build ${{ runner.workspace }}/build --config Release --parallel 4 --target example_plugin_vst3_plugin
    - run: cmake --build ${{ runner.workspace }}/build --config Debug --parallel 4 --target example_plugin_standalone_plugin
    - run: cmake --build ${{ runner.workspace }}/build --config Release --parallel 4 --target example_plugin_standalone_plugin
