name: Clang Format

on:
  push:
    paths:
      - "**/examples/**"
      - "**/modules/**"
      - "**/standalone/**"
      - "**/tests/**"
    branches:
      - "**"
      - "!main"

jobs:
  format:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            **/*.c
            **/*.cpp
            **/*.h
            **/*.hpp
            **/*.mm
            **/*.m
            !**/pybind11/**
            !**/thirdparty/**

      - name: Run clang-format
        working-directory: ${{ github.workspace }}
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          if [ -n "${ALL_CHANGED_FILES}" ]; then
            echo ${ALL_CHANGED_FILES}
            pipx run clang-format --version
            pipx run clang-format -style=file -i ${ALL_CHANGED_FILES}
            git diff
          fi

      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Code formatting
          commit_user_name: Yup Bot
          commit_user_email: yup-bot@users.noreply.github.com
          commit_author: Yup Bot <yup-bot@users.noreply.github.com>
